# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHeaderView, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QStackedWidget,
    QTableWidget, QTableWidgetItem, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(808, 486)
        MainWindow.setWindowTitle(u"iWallet")
        icon = QIcon(QIcon.fromTheme(u"accessories-calculator"))
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(130, 0, 671, 481))
        self.IncomePage = QWidget()
        self.IncomePage.setObjectName(u"IncomePage")
        self.IP_IncomeTable = QTableWidget(self.IncomePage)
        self.IP_IncomeTable.setObjectName(u"IP_IncomeTable")
        self.IP_IncomeTable.setGeometry(QRect(0, 40, 661, 401))
        self.IP_CommandBox = QComboBox(self.IncomePage)
        self.IP_CommandBox.setObjectName(u"IP_CommandBox")
        self.IP_CommandBox.setGeometry(QRect(510, 10, 69, 22))
        self.IP_DoButton = QPushButton(self.IncomePage)
        self.IP_DoButton.setObjectName(u"IP_DoButton")
        self.IP_DoButton.setGeometry(QRect(590, 10, 75, 24))
        self.IP_DateInput = QTextEdit(self.IncomePage)
        self.IP_DateInput.setObjectName(u"IP_DateInput")
        self.IP_DateInput.setGeometry(QRect(423, 10, 81, 21))
        self.IP_DateInput.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IP_DateInput.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IP_DateTxt = QLabel(self.IncomePage)
        self.IP_DateTxt.setObjectName(u"IP_DateTxt")
        self.IP_DateTxt.setGeometry(QRect(390, 10, 31, 16))
        self.IP_AmountInput = QTextEdit(self.IncomePage)
        self.IP_AmountInput.setObjectName(u"IP_AmountInput")
        self.IP_AmountInput.setGeometry(QRect(300, 10, 81, 21))
        self.IP_AmountInput.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IP_AmountInput.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IP_AmountTxt = QLabel(self.IncomePage)
        self.IP_AmountTxt.setObjectName(u"IP_AmountTxt")
        self.IP_AmountTxt.setGeometry(QRect(250, 10, 41, 16))
        self.IP_IDInput = QTextEdit(self.IncomePage)
        self.IP_IDInput.setObjectName(u"IP_IDInput")
        self.IP_IDInput.setGeometry(QRect(200, 10, 41, 21))
        self.IP_IDInput.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IP_IDInput.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IP_IDTxt = QLabel(self.IncomePage)
        self.IP_IDTxt.setObjectName(u"IP_IDTxt")
        self.IP_IDTxt.setGeometry(QRect(180, 10, 16, 16))
        self.IP_IncomeRes = QLabel(self.IncomePage)
        self.IP_IncomeRes.setObjectName(u"IP_IncomeRes")
        self.IP_IncomeRes.setGeometry(QRect(100, 440, 381, 41))
        self.IP_ResText = QLabel(self.IncomePage)
        self.IP_ResText.setObjectName(u"IP_ResText")
        self.IP_ResText.setGeometry(QRect(0, 440, 101, 41))
        self.stackedWidget.addWidget(self.IncomePage)
        self.OutcomePage = QWidget()
        self.OutcomePage.setObjectName(u"OutcomePage")
        self.OP_IDTxt = QLabel(self.OutcomePage)
        self.OP_IDTxt.setObjectName(u"OP_IDTxt")
        self.OP_IDTxt.setGeometry(QRect(180, 10, 16, 16))
        self.OP_AmountInput = QTextEdit(self.OutcomePage)
        self.OP_AmountInput.setObjectName(u"OP_AmountInput")
        self.OP_AmountInput.setGeometry(QRect(300, 10, 81, 21))
        self.OP_AmountInput.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.OP_AmountInput.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.OP_DateTxt = QLabel(self.OutcomePage)
        self.OP_DateTxt.setObjectName(u"OP_DateTxt")
        self.OP_DateTxt.setGeometry(QRect(390, 10, 31, 16))
        self.OP_IDInput = QTextEdit(self.OutcomePage)
        self.OP_IDInput.setObjectName(u"OP_IDInput")
        self.OP_IDInput.setGeometry(QRect(200, 10, 41, 21))
        self.OP_IDInput.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.OP_IDInput.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.OP_DoButton = QPushButton(self.OutcomePage)
        self.OP_DoButton.setObjectName(u"OP_DoButton")
        self.OP_DoButton.setGeometry(QRect(590, 10, 75, 24))
        self.OP_CommandBox = QComboBox(self.OutcomePage)
        self.OP_CommandBox.setObjectName(u"OP_CommandBox")
        self.OP_CommandBox.setGeometry(QRect(510, 10, 69, 22))
        self.OP_OutComeTable = QTableWidget(self.OutcomePage)
        self.OP_OutComeTable.setObjectName(u"OP_OutComeTable")
        self.OP_OutComeTable.setGeometry(QRect(0, 40, 671, 411))
        self.OP_DateInput = QTextEdit(self.OutcomePage)
        self.OP_DateInput.setObjectName(u"OP_DateInput")
        self.OP_DateInput.setGeometry(QRect(423, 10, 81, 21))
        self.OP_DateInput.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.OP_DateInput.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.OP_AmountTxt = QLabel(self.OutcomePage)
        self.OP_AmountTxt.setObjectName(u"OP_AmountTxt")
        self.OP_AmountTxt.setGeometry(QRect(250, 10, 41, 16))
        self.OP_ResText = QLabel(self.OutcomePage)
        self.OP_ResText.setObjectName(u"OP_ResText")
        self.OP_ResText.setGeometry(QRect(100, 450, 381, 31))
        self.Date1Text1_4 = QLabel(self.OutcomePage)
        self.Date1Text1_4.setObjectName(u"Date1Text1_4")
        self.Date1Text1_4.setGeometry(QRect(0, 450, 101, 31))
        self.stackedWidget.addWidget(self.OutcomePage)
        self.MainPage = QWidget()
        self.MainPage.setObjectName(u"MainPage")
        self.Date1Label = QLabel(self.MainPage)
        self.Date1Label.setObjectName(u"Date1Label")
        self.Date1Label.setGeometry(QRect(10, 10, 431, 41))
        self.Date1Text1 = QLabel(self.MainPage)
        self.Date1Text1.setObjectName(u"Date1Text1")
        self.Date1Text1.setGeometry(QRect(10, 50, 101, 41))
        self.Date1Text2 = QLabel(self.MainPage)
        self.Date1Text2.setObjectName(u"Date1Text2")
        self.Date1Text2.setGeometry(QRect(10, 80, 101, 41))
        self.Date1Income = QLabel(self.MainPage)
        self.Date1Income.setObjectName(u"Date1Income")
        self.Date1Income.setGeometry(QRect(110, 50, 381, 41))
        self.Date1Outcome = QLabel(self.MainPage)
        self.Date1Outcome.setObjectName(u"Date1Outcome")
        self.Date1Outcome.setGeometry(QRect(110, 80, 381, 41))
        self.Date1Label_2 = QLabel(self.MainPage)
        self.Date1Label_2.setObjectName(u"Date1Label_2")
        self.Date1Label_2.setGeometry(QRect(10, 110, 431, 41))
        self.Date1Income_2 = QLabel(self.MainPage)
        self.Date1Income_2.setObjectName(u"Date1Income_2")
        self.Date1Income_2.setGeometry(QRect(110, 150, 381, 41))
        self.Date1Outcome_2 = QLabel(self.MainPage)
        self.Date1Outcome_2.setObjectName(u"Date1Outcome_2")
        self.Date1Outcome_2.setGeometry(QRect(110, 180, 381, 41))
        self.Date1Text2_2 = QLabel(self.MainPage)
        self.Date1Text2_2.setObjectName(u"Date1Text2_2")
        self.Date1Text2_2.setGeometry(QRect(10, 180, 101, 41))
        self.Date1Text1_2 = QLabel(self.MainPage)
        self.Date1Text1_2.setObjectName(u"Date1Text1_2")
        self.Date1Text1_2.setGeometry(QRect(10, 150, 101, 41))
        self.Date1Label_3 = QLabel(self.MainPage)
        self.Date1Label_3.setObjectName(u"Date1Label_3")
        self.Date1Label_3.setGeometry(QRect(10, 220, 431, 41))
        self.Date1Income_3 = QLabel(self.MainPage)
        self.Date1Income_3.setObjectName(u"Date1Income_3")
        self.Date1Income_3.setGeometry(QRect(110, 260, 381, 41))
        self.Date1Outcome_3 = QLabel(self.MainPage)
        self.Date1Outcome_3.setObjectName(u"Date1Outcome_3")
        self.Date1Outcome_3.setGeometry(QRect(110, 290, 381, 41))
        self.Date1Text2_3 = QLabel(self.MainPage)
        self.Date1Text2_3.setObjectName(u"Date1Text2_3")
        self.Date1Text2_3.setGeometry(QRect(10, 290, 101, 41))
        self.Date1Text1_3 = QLabel(self.MainPage)
        self.Date1Text1_3.setObjectName(u"Date1Text1_3")
        self.Date1Text1_3.setGeometry(QRect(10, 260, 101, 41))
        self.Res3 = QLabel(self.MainPage)
        self.Res3.setObjectName(u"Res3")
        self.Res3.setGeometry(QRect(300, 280, 381, 41))
        self.Res2 = QLabel(self.MainPage)
        self.Res2.setObjectName(u"Res2")
        self.Res2.setGeometry(QRect(300, 160, 381, 41))
        self.Res1 = QLabel(self.MainPage)
        self.Res1.setObjectName(u"Res1")
        self.Res1.setGeometry(QRect(300, 60, 381, 41))
        self.stackedWidget.addWidget(self.MainPage)
        self.PassivePage = QWidget()
        self.PassivePage.setObjectName(u"PassivePage")
        self.PP_AmountTxt = QLabel(self.PassivePage)
        self.PP_AmountTxt.setObjectName(u"PP_AmountTxt")
        self.PP_AmountTxt.setGeometry(QRect(80, 0, 51, 41))
        self.PP_AmountTxt.setWordWrap(True)
        self.PP_IDInput = QTextEdit(self.PassivePage)
        self.PP_IDInput.setObjectName(u"PP_IDInput")
        self.PP_IDInput.setGeometry(QRect(30, 10, 41, 21))
        self.PP_IDInput.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PP_IDInput.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PP_PassiveIncomeTable = QTableWidget(self.PassivePage)
        self.PP_PassiveIncomeTable.setObjectName(u"PP_PassiveIncomeTable")
        self.PP_PassiveIncomeTable.setGeometry(QRect(0, 40, 661, 441))
        self.PP_IDTxt = QLabel(self.PassivePage)
        self.PP_IDTxt.setObjectName(u"PP_IDTxt")
        self.PP_IDTxt.setGeometry(QRect(10, 10, 16, 16))
        self.PP_DateTxt = QLabel(self.PassivePage)
        self.PP_DateTxt.setObjectName(u"PP_DateTxt")
        self.PP_DateTxt.setGeometry(QRect(220, 10, 31, 16))
        self.PP_DateInput = QTextEdit(self.PassivePage)
        self.PP_DateInput.setObjectName(u"PP_DateInput")
        self.PP_DateInput.setGeometry(QRect(253, 10, 81, 21))
        self.PP_DateInput.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PP_DateInput.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PP_AmountInput = QTextEdit(self.PassivePage)
        self.PP_AmountInput.setObjectName(u"PP_AmountInput")
        self.PP_AmountInput.setGeometry(QRect(130, 10, 81, 21))
        self.PP_AmountInput.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PP_AmountInput.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PP_DateTxt_2 = QLabel(self.PassivePage)
        self.PP_DateTxt_2.setObjectName(u"PP_DateTxt_2")
        self.PP_DateTxt_2.setGeometry(QRect(340, 10, 61, 16))
        self.PP_DoButton = QPushButton(self.PassivePage)
        self.PP_DoButton.setObjectName(u"PP_DoButton")
        self.PP_DoButton.setGeometry(QRect(580, 10, 75, 24))
        self.PP_CommandBox = QComboBox(self.PassivePage)
        self.PP_CommandBox.setObjectName(u"PP_CommandBox")
        self.PP_CommandBox.setGeometry(QRect(500, 10, 69, 22))
        self.PP_DateInput_2 = QTextEdit(self.PassivePage)
        self.PP_DateInput_2.setObjectName(u"PP_DateInput_2")
        self.PP_DateInput_2.setGeometry(QRect(400, 10, 81, 21))
        self.PP_DateInput_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PP_DateInput_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.stackedWidget.addWidget(self.PassivePage)
        self.IP_OpenButton = QPushButton(self.centralwidget)
        self.IP_OpenButton.setObjectName(u"IP_OpenButton")
        self.IP_OpenButton.setGeometry(QRect(10, 10, 111, 24))
        self.OP_OpenButton = QPushButton(self.centralwidget)
        self.OP_OpenButton.setObjectName(u"OP_OpenButton")
        self.OP_OpenButton.setGeometry(QRect(10, 40, 111, 24))
        self.PP_OpenButton = QPushButton(self.centralwidget)
        self.PP_OpenButton.setObjectName(u"PP_OpenButton")
        self.PP_OpenButton.setGeometry(QRect(10, 70, 111, 24))
        self.MP_OpenButton = QPushButton(self.centralwidget)
        self.MP_OpenButton.setObjectName(u"MP_OpenButton")
        self.MP_OpenButton.setGeometry(QRect(10, 100, 111, 24))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 160, 49, 16))
        self.LeaveButton = QPushButton(self.centralwidget)
        self.LeaveButton.setObjectName(u"LeaveButton")
        self.LeaveButton.setGeometry(QRect(10, 130, 111, 24))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.IP_DoButton.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
        self.IP_DateTxt.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0430\u0442\u0430", None))
        self.IP_AmountTxt.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0443\u043c\u043c\u0430", None))
        self.IP_IDTxt.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.IP_IncomeRes.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#126f0b;\">\u0426\u0438\u0444\u0440\u0430</span></p></body></html>", None))
        self.IP_ResText.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#126f0b;\">\u0414\u043e\u0445\u043e\u0434\u044b:</span></p></body></html>", None))
        self.OP_IDTxt.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.OP_DateTxt.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0430\u0442\u0430", None))
        self.OP_DoButton.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
        self.OP_AmountTxt.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0443\u043c\u043c\u0430", None))
        self.OP_ResText.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#126f0b;\">\u0426\u0438\u0444\u0440\u0430</span></p></body></html>", None))
        self.Date1Text1_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#6f0000;\">\u0420\u0430\u0441\u0445\u043e\u0434\u044b:</span></p></body></html>", None))
        self.Date1Label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt;\">\u0414\u0430\u0442\u04301</span></p></body></html>", None))
        self.Date1Text1.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#126f0b;\">\u0414\u043e\u0445\u043e\u0434\u044b:</span></p></body></html>", None))
        self.Date1Text2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#6f0002;\">\u0420\u0430\u0441\u0445\u043e\u0434\u044b:</span></p></body></html>", None))
        self.Date1Income.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#126f0b;\">\u0426\u0438\u0444\u0440\u0430</span></p></body></html>", None))
        self.Date1Outcome.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#6f0002;\">\u0426\u0438\u0444\u0440\u0430</span></p></body></html>", None))
        self.Date1Label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt;\">\u0414\u0430\u0442\u04301</span></p></body></html>", None))
        self.Date1Income_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#126f0b;\">\u0426\u0438\u0444\u0440\u0430</span></p></body></html>", None))
        self.Date1Outcome_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#6f0002;\">\u0426\u0438\u0444\u0440\u0430</span></p></body></html>", None))
        self.Date1Text2_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#6f0002;\">\u0420\u0430\u0441\u0445\u043e\u0434\u044b:</span></p></body></html>", None))
        self.Date1Text1_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#126f0b;\">\u0414\u043e\u0445\u043e\u0434\u044b:</span></p></body></html>", None))
        self.Date1Label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt;\">\u0414\u0430\u0442\u04301</span></p></body></html>", None))
        self.Date1Income_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#126f0b;\">\u0426\u0438\u0444\u0440\u0430</span></p></body></html>", None))
        self.Date1Outcome_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#6f0002;\">\u0426\u0438\u0444\u0440\u0430</span></p></body></html>", None))
        self.Date1Text2_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#6f0002;\">\u0420\u0430\u0441\u0445\u043e\u0434\u044b:</span></p></body></html>", None))
        self.Date1Text1_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; color:#126f0b;\">\u0414\u043e\u0445\u043e\u0434\u044b:</span></p></body></html>", None))
        self.Res3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt; color:#126f0b;\">+15900</span></p></body></html>", None))
        self.Res2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt; color:#126f0b;\">+15900</span></p></body></html>", None))
        self.Res1.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt; color:#126f0b;\">+15900</span></p></body></html>", None))
        self.PP_AmountTxt.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0443\u043c\u043c\u0430 \u043f\u043e\u043a\u0443\u043f\u043a\u0438", None))
        self.PP_IDTxt.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.PP_DateTxt.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0430\u0442\u0430", None))
        self.PP_DateTxt_2.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0430\u0432\u043a\u0430, %", None))
        self.PP_DoButton.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
        self.IP_OpenButton.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0445\u043e\u0434\u044b", None))
        self.OP_OpenButton.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0441\u0445\u043e\u0434\u044b", None))
        self.PP_OpenButton.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0430\u0441\u0441\u0438\u0432\u043d\u044b\u0439 \u0434\u043e\u0445\u043e\u0434", None))
        self.MP_OpenButton.setText(QCoreApplication.translate("MainWindow", u"\u0413\u043b\u0430\u0432\u043d\u043e\u0435 \u043c\u0435\u043d\u044e", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.LeaveButton.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0445\u043e\u0434", None))
        pass
    # retranslateUi

